deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
    - key: hive.openshift.io/version-major-minor
      operator: In
      values: ["4.6", "4.7", "4.8"]
    - key: ext-managed.openshift.io/uwm-disabled
      operator: NotIn
      values: ["true"]
    - key: api.openshift.com/environment
      operator: In
      values: ["production"]
    - key: api.openshift.com/legal-entity-id
      operator: In
      values: ${{SCALE_TEST_LEGALENTITY_IDS}}
